[package]
name = "neolink_decoder"
description = "A cli decoder for the AES encrypted packets"
version = "0.6.3-rc.3"
authors = ["Andrew King <sheepchaan@gmail.com>"]
edition = "2018"
rust-version = "1.88"
license = "AGPL-3.0-or-later"

[dependencies]
aes = "0.8.4"
anyhow = "1.0.104"
cfb-mode = "0.8.2"
env_logger = "0.11.11"
hex-string = "0.1.0"
md5 = "0.8.1"
requestty = "0.6.3"
log = "0.4.33"
